apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Tool\kompose.exe convert -f .\docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: engine
  name: engine
  namespace: devops-model
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 5002
  selector:
    io.kompose.service: engine