apiVersion: v1
kind: Service
metadata:
  name: keda-interceptor
  namespace: dev
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
  ports:
    - port: 8080