apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Tool\kompose.exe convert -f .\docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: manager
  name: manager
  namespace: dev
spec:
  type: LoadBalancer
  loadBalancerIP: ${AKS_PUBLIC_IP} # Use the public IP from the cluster
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    io.kompose.service: manager