version: "3.9"

services:

  # -------------------- Azure SQL Edge --------------------
  sqledge:
    container_name: sqledge
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: "${ACCEPT_EULA}"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    networks:
      sb-emulator:

  # -------------------- Azure Service Bus Emulator --------------------
  servicebus-emulator:
    container_name: servicebus-emulator
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
       - ./servicebus-emulator:/ServiceBus_Emulator/ConfigFiles

    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      ACCEPT_EULA: "${ACCEPT_EULA}"
    depends_on:
      - sqledge
    networks:
      sb-emulator:

  # ------------------------ Manager Service ---------------------------
  manager:
    build:
      context: ./Manager
    container_name: manager
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001
    depends_on:
      - servicebus-emulator
    networks:
      - microservice-net
      - sb-emulator

  manager-dapr:
    image: "daprio/daprd:latest"
    container_name: manager-dapr
    depends_on:
      - manager
    command: [
      "./daprd",
      "-app-id", "manager",
      "-app-port", "5001",
      "-placement-host-address", "placement:50006",
      "-dapr-http-port", "3500",
      "--resources-path", "/dapr/components",
      "-config", "/dapr/config.yaml"
    ]
    volumes:
      - ./dapr:/dapr
    networks:
      - microservice-net

  # ------------------------ Engine Service ---------------------------
  engine:
    build:
      context: ./Engine
    container_name: engine
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_URLS=http://+:5002
    depends_on:
      - servicebus-emulator
    networks:
      - microservice-net
      - sb-emulator

  engine-dapr:
    image: "daprio/daprd:latest"
    container_name: engine-dapr
    depends_on:
      - engine
    command: [
      "./daprd",
      "-app-id", "engine",
      "-app-port", "5002",
      "-placement-host-address", "placement:50006",
      "-dapr-http-port", "3501",
      "--resources-path", "/dapr/components",
      "-config", "/dapr/config.yaml"
    ]
    volumes:
      - ./dapr:/dapr
    networks:
      - microservice-net

  # ------------------------ Accessor Service ---------------------------
  accessor:
    build:
      context: ./Accessor
    container_name: accessor
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_URLS=http://+:5003
    depends_on:
      - servicebus-emulator
    networks:
      - microservice-net
      - sb-emulator

  accessor-dapr:
    image: "daprio/daprd:latest"
    container_name: accessor-dapr
    depends_on:
      - accessor
    command: [
      "./daprd",
      "-app-id", "accessor",
      "-app-port", "5003",
      "-placement-host-address", "placement:50006",
      "-dapr-http-port", "3502",
      "--resources-path", "/dapr/components",
      "-config", "/dapr/config.yaml"
    ]
    volumes:
      - ./dapr:/dapr
    networks:
      - microservice-net

# ------------------------ Shared Networks ---------------------------
networks:
  microservice-net:
    driver: bridge
  sb-emulator:
    driver: bridge
