apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: engine-to-accessor-input
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
    - name: connectionString
      value: "Endpoint=sb://host.docker.internal/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=localSecret;UseDevelopmentEmulator=true;"
    - name: queueName
      value: "engine-to-accessor"
    - name: direction
      value: input
    - name: disableEntityManagement
      value: "true"
scopes:
  - accessor
