apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: host
      value: "amqp://user:pass@rabbitmq:5672"
    - name: durable
      value: "true"
    - name: prefetchCount
      value: "50"
    - name: backOffDuration
      value: "5s"
    - name: backOffMaxRetries
      value: "3"
    - name: deadLetterTopic
      value: "ai-dead"
    - name: requeueInFailure
      value: "true"
  scopes:
    - manager
    - engine