loki:
  enabled: true
  deploymentMode: StatefulSet
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
promtail:
  enabled: true
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  extraVolumes:
    - name: varlog
      hostPath:
        path: /var/log
  extraVolumeMounts:
    - name: varlog
      mountPath: /var/log
      readOnly: true
  config:
    snippets:
      pipelineStages:
        - cri: {}
        - json:
            expressions:
              TraceId0: Scopes[0].TraceId
              TraceId1: Scopes[1].TraceId
              TraceId2: Scopes[2].TraceId
              SpanId0: Scopes[0].SpanId
              SpanId1: Scopes[1].SpanId
              SpanId2: Scopes[2].SpanId
        - template:
            source: TraceId0
            dest: TraceId
            template: '{{ if .TraceId0 }}{{ .TraceId0 }}{{ else if .TraceId1 }}{{ .TraceId1 }}{{ else }}{{ .TraceId2 }}{{ end }}'
        - template:
            source: SpanId0
            dest: SpanId
            template: '{{ if .SpanId0 }}{{ .SpanId0 }}{{ else if .SpanId1 }}{{ .SpanId1 }}{{ else }}{{ .SpanId2 }}{{ end }}'
        - labels:
            TraceId:
            SpanId: