apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmosdb-emulator
  namespace: devops-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmosdb-emulator
  template:
    metadata:
      labels:
        app: cosmosdb-emulator
    spec:
      containers:
        - name: cosmosdb-emulator
          image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
          ports:
            - containerPort: 8081  # HTTPS port for emulator
            - containerPort: 10250 # Emulator control (optional)
          env:
            - name: AZURE_COSMOS_EMULATOR_PARTITION_COUNT
              value: "3"
            - name: AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE
              value: "true"
            - name: AZURE_COSMOS_EMULATOR_ALLOW_NETWORK_ACCESS
              value: "true"
            - name: AZURE_COSMOS_EMULATOR_NOUI
              value: "true"
            - name: AZURE_COSMOS_EMULATOR_ENABLE_PREVIEW
              value: "true"
            - name: AZURE_COSMOS_EMULATOR_CERTIFICATE_POLICY
              value: accept_certificate
          volumeMounts:
            - name: cosmosdata
              mountPath: /tmp/cosmos/appdata
      volumes:
        - name: cosmosdata
          emptyDir: {}
