apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: pgdata
  name: pgdata
  namespace: devops-model
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
