# DEV overrides for the Helm chart
global:
  dockerRegistry: ""   # CI sets: docker.io/<org> or <acr>.azurecr.io
  imagePullPolicy: IfNotPresent
  dapr:
    enabled: true
    configName: dapr-config

namespace:
  create: true
  name: dev

manager:
  image:
    tag: dev               # dev tag (or a short SHA)
  # service, ports, labels inherit from base values.yaml
  env:
    ASPNETCORE_URLS: "http://+:5001"
  # secrets inherit from base values.yaml
  ingress:
    enabled: true
    host: teachin.westeurope.cloudapp.azure.com
    basePath: /api
    tls:
      enabled: true
      clusterIssuer: letsencrypt-prod
      secretName: teachin-tls
      
engine:
  image:
    tag: dev
  env:
    ASPNETCORE_URLS: "http://+:5002"
    AzureOpenAI__Endpoint: "https://france-teachin-open-ai.openai.azure.com/"
    AzureOpenAI__ApiKey: ""     # injecting via secret/CI
    AzureOpenAI__DeploymentName: "gpt-4.1-mini"
    AzureOpenAI__ModelId: "gpt-4o-mini"
    AzureSpeech__SubscriptionKey: ""
    AzureSpeech__Region: "eastus"
    AzureSpeech__DefaultVoice: "he-IL-HilaNeural"
    AzureSpeech__TimeoutSeconds: "70"

accessor:
  image:
    tag: dev
  env:
    ASPNETCORE_URLS: "http://+:5003"
