# Template values file for temporary environments (test*, feat*, pr*, etc.)
# Copy this file and rename to values.{environment-name}.yaml for specific environments
# Example: values.featest.yaml, values.test123.yaml, values.pr456.yaml

global:
  dockerRegistry: ""   # CI sets: docker.io/<org> or <acr>.azurecr.io
  imagePullPolicy: IfNotPresent
  environment: ""      # Will be set by CI/CD to TARGET_NAMESPACE
  dapr:
    enabled: true
    configName: dapr-config

namespace:
  create: true
  name: ""  # Will be set dynamically to TARGET_NAMESPACE

manager:
  image:
    name: manager
    # tag will be set dynamically via global.environment by CI/CD
  env:
    ASPNETCORE_URLS: "http://+:5001"
  # secrets inherit from base values.yaml
  ingress:
    enabled: true
    host: teachin.westeurope.cloudapp.azure.com
    basePath: /api  # Shared API path - works for temporary environments
    tls:
      enabled: true
      clusterIssuer: letsencrypt-prod
      secretName: teachin-tls
      
engine:
  image:
    name: engine
    # tag will be set dynamically via global.environment by CI/CD
  env:
    ASPNETCORE_URLS: "http://+:5002"
    AzureOpenAI__Endpoint: "https://france-teachin-open-ai.openai.azure.com/"
    AzureOpenAI__ApiKey: ""     # injecting via secret/CI
    AzureOpenAI__DeploymentName: "gpt-4.1-mini"
    AzureOpenAI__ModelId: "gpt-4o-mini"
    AzureSpeech__SubscriptionKey: ""
    AzureSpeech__Region: "eastus"
    AzureSpeech__DefaultVoice: "he-IL-HilaNeural"
    AzureSpeech__TimeoutSeconds: "70"

accessor:
  image:
    name: accessor
    # tag will be set dynamically via global.environment by CI/CD
  env:
    ASPNETCORE_URLS: "http://+:5003"

# Frontend Static Web App Proxy - DISABLED for temporary environments
# This prevents DNS conflicts with permanent environments (dev, prod)
frontend:
  enabled: false  # Set to true only if you want frontend for this specific environment
  path: "/"
  staticWebApp:
    hostname: ""  # Only used when enabled=true
