apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: temp-teachin-ingress
  namespace: devops-logs
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "temp-letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - temp-teachin-zionet.westeurope.cloudapp.azure.com
      secretName: temp-teachin-zionet-tls
  rules:
  - host: temp-teachin-zionet.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 80