apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-backend
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      vaultUrl: https://teachin-seo-kv.vault.azure.net/
      identityId: 0997f44d-fadf-4be8-8dc6-202f7302f680   # aks-cluster-dev clientId
      tenantId: a814ee32-f813-4a36-9686-1b9268183e27     # Azure AD tenantId
      cloudName: AzurePublicCloud
