# cosmosdb-emulator-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cosmosdb-emulator
  namespace: devops-model
spec:
  type: NodePort
  selector:
    app: cosmosdb-emulator
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081   # <-- You can choose a port in the range 30000–32767
