apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: notificationmanager
  name: notificationmanager
  namespace: default
spec:
  type: NodePort
  ports:
    - name: "5072"
      port: 5072
      targetPort: 8080
      nodePort: 30072  # must be between 30000–32767
  selector:
    io.kompose.service: notificationmanager