apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: signalr
  name: signalr
  namespace: devops-model
  ##namespace: default
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
    - name: "7071"
      port: 7071
      targetPort: 7071
  selector:
    io.kompose.service: signalr