apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.30.0 (9d8dcb518)
    dapr.io/enabled: "true"
    dapr.io/app-id: "notificationmanager"
    dapr.io/app-port: "8080"
  creationTimestamp: null
  labels:
    io.kompose.service: todomanager
  name: todomanager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todomanager
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\kompose\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/democuest-democuest-dapr: "true"
        io.kompose.service: todomanager
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://todomanager:8080
          image: ${DOCKER_REGISTRY}/todomanager
          name: todomanager
          ports:
            - containerPort: 8080
              #hostPort: 5073
              protocol: TCP
          resources: {}
      restartPolicy: Always
