apiVersion: v1
kind: Secret
metadata:
  name: dapr-secretstore
  namespace: devops-model
type: Opaque
data:
  SignalRConnectionString: RW5kcG9pbnQ9aHR0cDovL2hvc3QuZG9ja2VyLmludGVybmFsOjg4ODg7UG9ydD04ODg4O0FjY2Vzc0tleT1BQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjAxMjM0NTY3ODlBRkJDRUZHSDtWZXJzaW9uPTEuMDs=
