apiVersion: v1
kind: ConfigMap
metadata:
  name: dapr-config
  namespace: dev
data:
  config.yaml: |
    apiVersion: dapr.io/v1alpha1
    kind: Configuration
    metadata:
      name: daprConfig
    spec:
      tracing:
        samplingRate: "1"
 