apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: manager-to-engine
  namespace: dev
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: azure-service-bus-secret
        key: AzureServiceBusConnectionString
    - name: queueName
      value: "manager-to-engine"
    - name: direction
      value: output
    - name: disableEntityManagement
      value: "true"
scopes:
  - manager
  - engine
