apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: ${ENVIRONMENT_NAME}
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: azure-service-bus-secret-${ENVIRONMENT_NAME}
        key: AzureServiceBusConnectionString
    - name: consumerID
      value: "engine"
    - name: disableEntityManagement
      value: "true"
scopes:
  - manager
  - engine
  - accessor