apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secret-store
  namespace: ${ENVIRONMENT_NAME}
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: vaultName
    value: ${ENVIRONMENT_NAME}