apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: taskupdate-input
  namespace: dev
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: azure-service-bus-secret
        key: AzureServiceBusConnectionString
    - name: queueName
      value: "taskupdate"
    - name: direction
      value: input
    - name: disableEntityManagement
      value: "true"
scopes:
  - accessor
