apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: accessor-scaledobject
  namespace: dev # Specify the namespace where this ScaledObject will be created
spec:
  scaleTargetRef:
    name: accessor
  minReplicaCount: 1
  maxReplicaCount: 4
  triggers:
    - type: azure-servicebus
      metadata:
        namespace: servicebus-dev-zionet-learning-2025-keda
        queueName: engine-to-accessor
        messageCount: "1" # scale when 1+ messages
        connectionFromEnv: ServiceBus__ConnectionString
