apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: manager-scaledobject
  namespace: dev # Specify the namespace where this ScaledObject will be created
spec:
  scaleTargetRef:
    name: manager
  minReplicaCount: 0
  maxReplicaCount: 3
  triggers:
    - type: http
      metadata:
        host: http://teaching-zionet.westeurope.cloudapp.azure.com/manager # The host URL for the HTTP trigger