apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: accessor-queue-out
  namespace: {{ include "app.namespace" . }}
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: azure-service-bus-secret
        key: AzureServiceBusConnectionString
    - name: queueName
      value: "accessor-queue"
    - name: direction
      value: output
    - name: disableEntityManagement
      value: "true"
scopes:
  - {{ .Values.manager.dapr.appId  | default .Values.manager.name  | quote }}