{{- $global      := .Values.global           | default dict -}}
{{- $globalDapr  := $global.dapr             | default dict -}}
{{- $globalName  := $globalDapr.configName   | default ""   -}}
{{- $dapr        := .Values.dapr             | default dict -}}
{{- $conf        := $dapr.configuration      | default dict -}}
{{- $name        := (or $conf.name $globalName "dapr-config") -}}

apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: {{ $name | lower | quote }}
  namespace: {{ include "app.namespace" . }}
spec:
  tracing:
    samplingRate: "1"
