apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: engine-queue-in
  namespace: {{ include "app.namespace" . }}
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: "{{ .Values.namespace.name }}-azure-service-bus-secret"
    - name: queueName
      value: "engine-queue"
    - name: direction
      value: input
    - name: disableEntityManagement
      value: "true"
scopes:
  - {{ .Values.manager.dapr.appId  | default .Values.manager.name  | quote }}
