apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ include "app.join" (list (include "app.prefix" .) "local-secret-store") }}
  namespace: {{ include "app.namespace" . }}
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: vaultName
    value: dev
