apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secret-store
  namespace: {{ include "app.namespace" . }}
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: "{{ .Values.global.environment }}-kv"   # Must match the Key Vault name created in Terraform
    - name: spnClientId
      value: "{{ .Values.global.keyvault.clientId }}"
    - name: spnClientSecret
      value: "{{ .Values.global.keyvault.clientSecret }}"
    - name: spnTenantId
      value: "{{ .Values.global.keyvault.tenantId }}"
