apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: placement
  name: placement
  namespace: devops-model
spec:
  ports:
    - name: "50006"
      port: 50006
      targetPort: 50006
  selector:
    io.kompose.service: placement