# --- crds.yaml snippet ---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: components.dapr.io
spec:
  group: dapr.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
  scope: Namespaced
  names:
    plural: components
    singular: component
    kind: Component
    shortNames:
      - comp
