apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Tool\kompose.exe convert -f .\docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: accessor
  name: accessor
  namespace: devops-model
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: accessor
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Tool\kompose.exe convert -f .\docker-compose.yaml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: accessor
    spec:
      containers:
        - env:
            - name: ASPNETCORE_URLS
              value: http://+:5003
            - name: DB_HOST
              value: postgres-db
            - name: DB_NAME
              value: postgres_db
            - name: DB_PASS
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
          image: snir1551/accessor:latest
          name: accessor
          ports:
            - containerPort: 5003
              protocol: TCP
        - args:
            - ./daprd
            - -app-id
            - accessor
            - -app-port
            - "5003"
            - -placement-host-address
            - placement:50006
            - -dapr-http-port
            - "3502"
            - --resources-path
            - /dapr/components
            - -config
            - /dapr/config.yaml
          image: daprio/daprd:latest
          name: accessor-dapr
          volumeMounts:
            - name: dapr-config
              mountPath: /dapr/config.yaml
              subPath: config.yaml
            - name: dapr-components
              mountPath: /dapr/components
      restartPolicy: Always
      volumes:
        - name: dapr-config
          configMap:
            name: dapr-config
        - name: dapr-components
          emptyDir: {}
