apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Tool\kompose.exe convert -f .\docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: sqledge
  name: sqledge
  namespace: devops-model
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sqledge
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Tool\kompose.exe convert -f .\docker-compose.yaml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: sqledge
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: YourStrongP@ssword123!
          image: mcr.microsoft.com/azure-sql-edge:latest
          name: sqledge
          ports:
            - containerPort: 1433
              protocol: TCP
      restartPolicy: Always
