apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: todoaccessor
  name: todoaccessor
  namespace: devops-model
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todoaccessor
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\kompose\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.30.0 (9d8dcb518)
        dapr.io/enabled: "true"
        dapr.io/app-id: "todoaccessor"
        dapr.io/app-port: "8080"
      creationTimestamp: null
      labels:
        io.kompose.network/democuest-democuest-dapr: "true"
        io.kompose.service: todoaccessor
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: TodoCosmosDbSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: cosmosdb-connection
                  key: CosmosDbConnectionString
            - name: TodoCosmosDbSettings__DatabaseName
              value: ToDoDatabase
            - name: TodoCosmosDbSettings__ContainerName
              value: ToDos
          image: ${DOCKER_REGISTRY}/todoaccessor
          name: todoaccessor
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always