apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: dev # Specify the namespace where this secret will be created
type: Opaque
data:
  db-user: cG9zdGdyZXM= # Base64 encoded value for 'postgres'
  db-password: cG9zdGdyZXM= # Base64 encoded value for 'postgres'