apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: clientcallback
spec:
  type: bindings.azure.signalr
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: SignalRConnectionString
      key: SignalRConnectionString # dapr secret store
  - name: hub 
    value: todohub
auth:
  secretStore: local-secret-store
scopes:
  - notificationmanager    