apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: placement
  name: placement
  namespace: devops-model
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: placement
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\kompose\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/democuest-democuest-dapr: "true"
        io.kompose.service: placement
    spec:
      containers:
        - args:
            - ./placement
            - -port
            - "50006"
            - --log-level
            - debug
          image: daprio/dapr:1.13.5
          name: placement
          ports:
            - containerPort: 50006
              hostPort: 50006
              protocol: TCP
          resources: {}
      restartPolicy: Always
