apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Tool\kompose.exe convert -f .\docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: postgres
  name: postgres
  namespace: devops-model
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: postgres
