apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Tool\kompose.exe convert -f .\docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: servicebus-emulator
  name: servicebus-emulator
  namespace: devops-model
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "5300"
      port: 5300
      targetPort: 5300
  selector:
    io.kompose.service: servicebus-emulator
