apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Tool\kompose.exe convert -f .\docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: sqledge
  name: sqledge
  namespace: devops-model
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    io.kompose.service: sqledge
