apiVersion: apps/v1 
kind: Deployment
metadata: # This metadata section contains information about the deployment
  name: accessor-${ENVIRONMENT_NAME}
  namespace: ${ENVIRONMENT_NAME} # Specify the namespace where this deployment will be created
  labels:
    app: accessor
    environment: ${ENVIRONMENT_NAME}
spec:
  replicas: 1 # Number of pod replicas
  selector: # This selector is used to find which pods to manage
    matchLabels: # This selector matches the labels of the pods managed by this deployment
      app: accessor
      environment: ${ENVIRONMENT_NAME}
  template: # This template defines the pod that will be created
    metadata:
      labels:
        app: accessor
        environment: ${ENVIRONMENT_NAME}
      annotations: # Annotations for the pod, useful for Dapr configuration
        dapr.io/enabled: "true" # Enable Dapr for this pod
        dapr.io/app-id: "accessor-${ENVIRONMENT_NAME}" # Dapr application ID
        dapr.io/app-port: "5003"  # Dapr app port
        dapr.io/sidecar-cpu-request: "100m"
        dapr.io/sidecar-memory-request: "128Mi"
        dapr.io/sidecar-cpu-limit: "200m"
        dapr.io/sidecar-memory-limit: "256Mi"
    spec: # This spec defines the pod's containers and their configurations
      containers:
        - name: accessor
          image: ${DOCKER_REGISTRY}/accessor:latest
          ports:
          - containerPort: 5003 # Port on which the application listens
          env:
          - name: ASPNETCORE_URLS
            value: "http://+:5003"
          - name: ServiceBus__ConnectionString
            valueFrom:
              secretKeyRef:
                name: azure-service-bus-secret-${ENVIRONMENT_NAME}
                key: AzureServiceBusConnectionString
          - name: ConnectionStrings__Postgres
            valueFrom:
              secretKeyRef:
                name: postgres-connection-${ENVIRONMENT_NAME}
                key: PostgreSQLConnectionString
          - name: ENVIRONMENT  
            value: ${ENVIRONMENT_NAME}
          resources:
            requests:
              memory: "256Mi" 
              cpu: "250m"     
            limits:
              memory: "512Mi" 
              cpu: "500m"     
      serviceAccountName: ${ENVIRONMENT_NAME}-serviceaccount
