apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Tool\kompose.exe convert -f .\docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: engine
  name: engine
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: engine
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Tool\kompose.exe convert -f .\docker-compose.yaml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: engine
    spec:
      containers:
        - env:
            - name: ASPNETCORE_URLS
              value: http://+:5002
          image: ${DOCKER_REGISTRY}/engine:latest
          name: engine
          ports:
            - containerPort: 5002
              protocol: TCP
        - args:
            - ./daprd
            - -app-id
            - engine
            - -app-port
            - "5002"
            - -placement-host-address
            - placement:50006
            - -dapr-http-port
            - "3501"
            - --resources-path
            - /dapr/components
            - -config
            - /dapr/config.yaml
          image: daprio/daprd:latest
          name: engine-dapr
          volumeMounts:
            - name: dapr-config
              mountPath: /dapr/config.yaml
              subPath: config.yaml
            - name: dapr-components
              mountPath: /dapr/components
      restartPolicy: Always
      volumes:
        - name: dapr-config
          configMap:
            name: dapr-config
        - name: dapr-components
          emptyDir: {}