apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Tool\kompose.exe convert -f .\docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: manager
    environment: ${ENVIRONMENT_NAME}
  name: manager-${ENVIRONMENT_NAME}
  namespace: ${ENVIRONMENT_NAME} 
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: manager
      environment: ${ENVIRONMENT_NAME}
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "manager-${ENVIRONMENT_NAME}"
        dapr.io/app-port: "5001"
        dapr.io/sidecar-cpu-request: "100m"
        dapr.io/sidecar-memory-request: "128Mi"
        dapr.io/sidecar-cpu-limit: "200m"
        dapr.io/sidecar-memory-limit: "256Mi"
        kompose.cmd: D:\Tool\kompose.exe convert -f .\docker-compose.yaml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: manager
        environment: ${ENVIRONMENT_NAME}
    spec:
      containers:
        - env:
            - name: ASPNETCORE_URLS
              value: http://+:5001
            - name: ServiceBus__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: azure-service-bus-secret-${ENVIRONMENT_NAME}  
                  key: AzureServiceBusConnectionString

          image: ${DOCKER_REGISTRY}/manager:latest
          name: manager
          ports:
            - containerPort: 5001
              protocol: TCP
          resources:  
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always
      serviceAccountName: ${ENVIRONMENT_NAME}-serviceaccount