apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Tool\kompose.exe convert -f .\docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: manager
  name: manager
  namespace: newdev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: manager
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true" # Enable Dapr for this pod
        dapr.io/app-id: "manager" # Dapr application ID
        dapr.io/app-port: "5001"  # Dapr app port
        kompose.cmd: D:\Tool\kompose.exe convert -f .\docker-compose.yaml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: manager
    spec:
      containers:
        - env:
            - name: ASPNETCORE_URLS
              value: http://+:5001
            - name: ServiceBus__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: azure-service-bus-secret
                  key: AzureServiceBusConnectionString

          image: ${ACR_NAME}.azurecr.io/manager:latest
          name: manager
          ports:
            - containerPort: 5001
              protocol: TCP
      restartPolicy: Always