name: Deploy App to AKS

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    outputs:
      app_url:
        description: "Full URL of the deployed todomanager service"
        value: ${{ jobs.deploy.outputs.app_url }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read

    outputs:
      app_url: ${{ steps.extract_url.outputs.app_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set script as executable
        run: chmod +x ./start-cloud.sh

      - name: Run deployment script
        run: ./start-cloud.sh
        working-directory: ./devops/kubernetes/DemoCuest

      - name: Extract External URL of todomanager
        id: extract_url
        run: |
          echo "Extracting external IP of todomanager service..."
          IP=$(kubectl -n devops-model get svc todomanager -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          
          if [[ -z "$IP" ]]; then
            echo "Error: External IP not found."
            exit 1
          fi

          FULL_URL="http://$IP:5073/swagger"
          echo "app_url=$FULL_URL" >> $GITHUB_OUTPUT
          echo "App URL: $FULL_URL"


