name: AKS - Full CICD Demo

on:
  #push:
   # branches:
    #  - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'Development'
        type: choice
        options:
          - Development
          - Production

jobs:
  build-and-push-images:
    uses: ./.github/workflows/build-and-push-images-demo.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit

  aks-terraform-apply:
    uses: ./.github/workflows/aks-terraform-apply-demo.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: ${{ github.event.inputs.environment || 'Development' }}
    secrets: inherit

  aks-kubectl-apply:
    needs: [build-and-push-images, aks-terraform-apply]
    uses: ./.github/workflows/aks-kubectl-apply-demo.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: ${{ github.event.inputs.environment || 'Development' }}
    secrets: inherit

  healthcheck:
    needs: [aks-kubectl-apply]
    uses: ./.github/workflows/aks-healthcheck-demo.yml
    with:
      app_url: ${{ needs.aks-kubectl-apply.outputs.app_url }}
      environment: ${{ github.event.inputs.environment || 'Development' }}
    secrets: inherit