name: AKS - Stop Cluster (Evening)

on:
  schedule:
    # 19:30 Israel time = 17:30 UTC (during standard time) or 16:30 UTC (during DST)
    # Using 16:30 UTC to cover DST - adjust if needed
    - cron: '30 16 * * 0-6'  # Sunday-Saturday
  workflow_dispatch:  # Allow manual trigger

jobs:
  stop-aks:
    runs-on: ubuntu-latest
    environment: Development
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up variables
        run: |
          echo "AKS_RG=dev-zionet-learning-2025" >> $GITHUB_ENV
          echo "AKS_NAME=aks-cluster-dev" >> $GITHUB_ENV

      - name: Check current time in Israel
        run: |
          ISRAEL_TIME=$(TZ='Asia/Jerusalem' date '+%Y-%m-%d %H:%M:%S %Z')
          echo "Current Israel time: $ISRAEL_TIME"
          DAY_OF_WEEK=$(TZ='Asia/Jerusalem' date '+%u')  # 1=Monday, 7=Sunday
          echo "Day of week: $DAY_OF_WEEK (1=Mon, 5=Fri, 6=Sat, 7=Sun)"

      - name: Stop AKS cluster
        run: |
          echo "Stopping AKS cluster: $AKS_NAME in resource group: $AKS_RG"
          az aks stop --resource-group $AKS_RG --name $AKS_NAME
          echo "AKS cluster stopped successfully"

      - name: Verify cluster status
        run: |
          STATUS=$(az aks show --resource-group $AKS_RG --name $AKS_NAME --query "powerState.code" -o tsv)
          echo "AKS cluster status: $STATUS"