name: AKS - Platform Setup (Ingress/Dapr/Monitoring)

run-name: >
  Platform for ${{
    inputs.environment_name != '' && format('custom:{0}', inputs.environment_name) ||
    github.event.inputs.environment_name != '' && format('custom:{0}', github.event.inputs.environment_name) ||
    'dev'
  }} [${{ inputs.environment || github.event.inputs.environment }}]

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (GitHub Environment)'
        required: true
        default: 'Development'
        type: choice
        options: [Development, Production]
      environment_name:
        description: 'Optional namespace/prefix (lowercase letters & digits). Empty -> dev'
        required: false
        default: ''
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      environment_name:
        required: false
        type: string
    outputs:
      ingress_url:
        description: "http://<ingress external IP>"
        value: ${{ jobs.platform.outputs.ingress_url }}

jobs:
  platform:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || github.event.inputs.environment }}
    permissions:
      id-token: write
      contents: read

    outputs:
      ingress_url: ${{ steps.wait_for_ingress_ip.outputs.ingress_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up variables
        run: |
          ENVIRONMENT_NAME="${{ inputs.environment_name || github.event.inputs.environment_name }}"
          if [ -n "$ENVIRONMENT_NAME" ]; then
            [[ "$ENVIRONMENT_NAME" =~ ^[a-z0-9]+$ ]] || { echo "environment_name must be ^[a-z0-9]+$"; exit 1; }
            echo "TARGET_NAMESPACE=$ENVIRONMENT_NAME" >> $GITHUB_ENV
            echo "RESOLVED_TARGET=custom($ENVIRONMENT_NAME)" >> $GITHUB_ENV
          else
            echo "TARGET_NAMESPACE=dev" >> $GITHUB_ENV
            echo "RESOLVED_TARGET=dev" >> $GITHUB_ENV
          fi

          echo "K8S_DIR=devops/kubernetes/" >> $GITHUB_ENV
          echo "CHART_DIR=devops/kubernetes/charts" >> $GITHUB_ENV

          # Shared AKS
          echo "AKS_RG=dev-zionet-learning-2025" >> $GITHUB_ENV
          echo "AKS_NAME=aks-cluster-dev" >> $GITHUB_ENV
          echo "MC_AKS_RG=MC_dev-zionet-learning-2025_aks-cluster-dev_westeurope" >> $GITHUB_ENV

          # PG (per env name)
          echo "PG_DB=${ENVIRONMENT_NAME}-pg-zionet-learning" >> $GITHUB_ENV
          echo "PG_RG=${ENVIRONMENT_NAME}-zionet-learning-2025" >> $GITHUB_ENV

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group $AKS_RG --name $AKS_NAME --overwrite-existing

      - name: Install/Upgrade Dapr control plane
        run: |
          cd devops/helm-tools
          chmod +x dapr-control-plane.sh
          ./dapr-control-plane.sh

      - name: Setup ingress controller
        run: |
          cd devops/helm-tools
          chmod +x setup-ingress-controller.sh
          ./setup-ingress-controller.sh

      - name: Add Grafana
        run: |
          cd devops/helm-tools
          chmod +x grafana.sh
          ./grafana.sh

      # - name: Setup HTTPS certificates
      #   run: |
      #     cd devops/helm-tools
      #     chmod +x setup-https.sh
      #     ./setup-https.sh

      - name: Apply Grafana ingress (only)
        run: kubectl apply -f "$K8S_DIR/ingress/grafana-ingress.yaml"

      - name: Add Prometheus
        run: |
          cd devops/helm-tools/prometheus
          chmod +x prometheus.sh
          ./prometheus.sh

      - name: Add Loki (logs stack)
        run: |
          cd devops/helm-tools/loki
          chmod +x loki.sh
          ./loki.sh

      - name: Wait for external IP for ingress controller
        id: wait_for_ingress_ip
        run: |
          echo "Waiting for external IP for ingress-nginx-controller..."
          for i in {1..30}; do
            INGRESS_IP=$(kubectl -n devops-ingress-nginx get svc ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            if [[ -n "$INGRESS_IP" ]]; then
              echo "Ingress IP is ready: $INGRESS_IP"
              echo "ingress_url=http://$INGRESS_IP" >> $GITHUB_OUTPUT
              exit 0
            fi
            echo "Attempt $i: not ready. Sleeping 10s..."
            sleep 10
          done
          echo "Failed to get ingress IP."; exit 1

      - name: Add ingress IP to PostgreSQL firewall
        run: |
          INGRESS_IP=$(kubectl -n devops-ingress-nginx get svc ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          az postgres flexible-server firewall-rule create \
            --resource-group $PG_RG \
            --name $PG_DB \
            --rule-name allow-ingress-controller \
            --start-ip-address $INGRESS_IP \
            --end-ip-address $INGRESS_IP

      - name: Restart logging stack pods (optional)
        run: kubectl delete pod --all -n devops-logs || true

      - name: Output external URL (if ingress exists)
        id: extract_url
        run: |
          INGRESS_IP=$(kubectl -n devops-ingress-nginx get svc ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || true)
          if [ -n "$INGRESS_IP" ]; then
            echo "app_url=http://$INGRESS_IP" >> $GITHUB_OUTPUT
            echo "App URL: http://$INGRESS_IP"
          else
            echo "app_url=" >> $GITHUB_OUTPUT
            echo "Ingress not found (run platform setup first if needed)."
          fi
