name: CI

on:
  push:
    branches:
      - add-component-test-ai  
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./backend/backend.sln

      - name: Build
        run: dotnet build ./backend/backend.sln --no-restore

      - name: Test
        run: dotnet test ./backend/Backend.ComponentTests/Backend.ComponentTests.csproj --no-build --verbosity normal