name: CI

on:
  push:
    branches:
      - add-component-test-ai
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./backend/ContainerApp/backend.sln

      - name: Build solution
        run: dotnet build ./backend/ContainerApp/backend.sln --no-restore

      - name: Run component tests
        run: dotnet test ./backend/ComponentTests/ComponentTests.csproj --no-build --verbosity normal