name: Clear Postgres Database

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "drop = DROP TABLE (removes structure), truncate = TRUNCATE (keeps tables)"
        required: true
        default: "drop"
        type: choice
        options:
          - drop
          - truncate
      dry_run:
        description: "If true, only print SQL and do not execute"
        required: false
        default: "true"
      verify_ssl:
        description: "true=require SSL (Azure default). false=disable SSL (NOT recommended)."
        required: false
        default: "true"

jobs:
  clear-db:
    runs-on: ubuntu-latest
    environment: Development
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read

    # Keep sensitive values in secrets where possible
    env:
      # Database connectivity
      PGHOST: dev-pg-zionet-learning.postgres.database.azure.com
      PGDATABASE: appdb-test
      PGUSER: ${{ secrets.POSTGRES_USER }}          # e.g. 'dbadmin' (Flexible Server: NO '@server' suffix)
      PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      MODE: ${{ github.event.inputs.mode }}
      DRY_RUN: ${{ github.event.inputs.dry_run }}
      VERIFY_SSL: ${{ github.event.inputs.verify_ssl }}

      # Azure infra (move to secrets if you prefer)
      AZURE_POSTGRES_SERVER: dev-pg-zionet-learning  # server name only (no domain)
      AZURE_RG: dev-zionet-learning-2025
      AZURE_SUB: 90ea4c2f-1eee-4ec9-927d-ed24c563003e

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Allow GitHub runner IP
        id: fw
        run: |
          set -euo pipefail
          RUNNER_IP=$(curl -s https://api.ipify.org)
          echo "runner_ip=$RUNNER_IP" >> "$GITHUB_OUTPUT"
          RULE="gha-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
          echo "Creating firewall rule $RULE for $RUNNER_IP"
          az postgres flexible-server firewall-rule create \
            --resource-group "$AZURE_RG" \
            --name "$AZURE_POSTGRES_SERVER" \
            --rule-name "$RULE" \
            --start-ip-address "$RUNNER_IP" \
            --end-ip-address "$RUNNER_IP"

      - name: Install psql client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client

      - name: Make scripts executable
        run: chmod +x .github/workflows/scripts/clear_postgres.sh

      - name: Clear Postgres
        run: .github/workflows/scripts/clear_postgres.sh

      # Always remove the firewall rule even if the job fails
      - name: Remove firewall rule
        if: always()
        run: |
          set -euo pipefail
          RULE="gha-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
          az postgres flexible-server firewall-rule delete \
            --resource-group "$AZURE_RG" \
            --name "$AZURE_POSTGRES_SERVER" \
            --rule-name "$RULE" \
            --yes
