name: Run component tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: true
        default: 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./backend/ContainerApp/backend.sln

      - name: Build solution
        run: dotnet build ./backend/ContainerApp/backend.sln --no-restore

      - name: Run component tests
        run: dotnet test ./backend/ComponentTests/ComponentTests.csproj --no-build --verbosity normal