name: Full CICD

on:
  # push:
  #  branches:
  #    - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'Development'
        type: choice
        options:
          - Development
          - Production

jobs:
  build-and-push-images:
    uses: ./.github/workflows/build-and-push-images.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit

  terraform-apply:
    uses: ./.github/workflows/terraform-apply.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: ${{ github.event.inputs.environment || 'Development' }}
    secrets: inherit

  aks-kubectl-apply:
    needs: [build-and-push-images, terraform-apply]
    uses: ./.github/workflows/aks-kubectl-apply.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: ${{ github.event.inputs.environment || 'Development' }}
    secrets: inherit

  deploy-frontend:
    needs: [terraform-apply]
    uses: ./.github/workflows/deploy-frontend.yml
    permissions:
      contents: read
    with:
      deployment_token: ${{ needs.terraform-apply.outputs.static_web_app_api_token }}
      app_insights_connection_string: ${{ needs.terraform-apply.outputs.app_insights_connection_string }}
    secrets: inherit

