name: Manual Deploy Existing Images

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Namespace/environment name (e.g., dev, dev2)'
        required: true
        type: string
      service:
        description: 'Service to update (or "all")'
        required: true
        default: 'all'
        type: choice
        options: [all, accessor, manager, engine]
      image_hashes:
        description: 'Comma-separated short hashes (e.g., abc1234,def5678,ghi9012 for all)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Development # This is the crucial line you need to add or update
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up variables
        run: |
          ENVIRONMENT_NAME="${{ inputs.environment_name || github.event.inputs.environment_name }}"
          if [ -n "$ENVIRONMENT_NAME" ]; then
            [[ "$ENVIRONMENT_NAME" =~ ^[a-z0-9]+$ ]] || { echo "environment_name must be ^[a-z0-9]+$"; exit 1; }
            echo "TARGET_NAMESPACE=$ENVIRONMENT_NAME" >> $GITHUB_ENV
            echo "RESOLVED_TARGET=custom($ENVIRONMENT_NAME)" >> $GITHUB_ENV
          else
            echo "TARGET_NAMESPACE=dev" >> $GITHUB_ENV
            echo "RESOLVED_TARGET=dev" >> $GITHUB_ENV
          fi

          echo "K8S_DIR=devops/kubernetes/" >> $GITHUB_ENV
          echo "CHART_DIR=devops/kubernetes/charts" >> $GITHUB_ENV

          # Shared AKS
          echo "AKS_RG=dev-zionet-learning-2025" >> $GITHUB_ENV
          echo "AKS_NAME=aks-cluster-dev" >> $GITHUB_ENV
          echo "MC_AKS_RG=MC_dev-zionet-learning-2025_aks-cluster-dev_westeurope" >> $GITHUB_ENV

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group $AKS_RG --name $AKS_NAME --overwrite-existing

      - name: Deploy selected images
        run: |
          SERVICES=("accessor" "manager" "engine")
          IFS=',' read -ra HASHES <<< "${{ github.event.inputs.image_hashes }}"
          NAMESPACE="${{ github.event.inputs.environment_name }}"
          SELECTED="${{ github.event.inputs.service }}"

          if [[ "$SELECTED" == "all" ]]; then
            for i in "${!SERVICES[@]}"; do
              SERVICE="${SERVICES[$i]}"
              HASH="${HASHES[$i]// /}"  # Remove spaces

              if [ -z "$HASH" ]; then
                echo "Missing hash for $SERVICE"
                exit 1
              fi

              echo "Updating $SERVICE to $HASH in namespace $NAMESPACE"
              helm upgrade $SERVICE ./devops/kubernetes/charts/chart \
                --install \
                --namespace "$NAMESPACE" \
                --set ${SERVICE}.image.name=${{ secrets.DOCKER_USERNAME }}/$SERVICE \
                --set ${SERVICE}.image.tag="$HASH"
            done
          else
            SERVICE="$SELECTED"
            HASH="${HASHES[0]// /}"

            echo "Updating $SERVICE to $HASH in namespace $NAMESPACE"
            helm upgrade $SERVICE ./devops/kubernetes/charts/chart \
              --install \
              --namespace "$NAMESPACE" \
              --set ${SERVICE}.image.name=${{ secrets.DOCKER_USERNAME }}/$SERVICE \
              --set ${SERVICE}.image.tag="$HASH" \
              --set ${SERVICE}.image.altTag="$NAMESPACE"
          fi