name: Run Unit Tests (All)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - name: EngineUnitTests
            path: backend/ContainerApp/UnitTests/EngineUnitTests/EngineUnitTests.csproj
          - name: AccessorUnitTests
            path: backend/ContainerApp/UnitTests/AccessorUnitTests/AccessorUnitTests.csproj
          - name: ManagerUnitTests
            path: backend/ContainerApp/UnitTests/ManagerUnitTests/ManagerUnitTests.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          # no caching — keeps it simple and avoids the lockfile error

      - name: Restore (solution)
        run: dotnet restore backend/ContainerApp/backend.sln

      - name: Build (solution)
        run: dotnet build backend/ContainerApp/backend.sln --no-restore -c Release

      - name: Test – ${{ matrix.project.name }}
        run: dotnet test "${{ matrix.project.path }}" --no-build -c Release --verbosity normal
