name: Run Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore backend.sln
      working-directory: backend/ContainerApp

    - name: Build
      run: dotnet build --no-restore
      working-directory: backend/ContainerApp

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
