name: Run Component Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'backend/ContainerApp/Engine/**'
      - 'backend/ContainerApp/EngineComponentTests/**'
      - 'backend/ContainerApp/Directory.Build.props'
      - '.github/workflows/**'
  workflow_dispatch:

concurrency:
  group: component-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set-services.outputs.services }}
    steps:
      - uses: actions/checkout@v4

      - name: Detect changed services
        id: filter
        uses: dorny/paths-filter@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            engine:
              - 'backend/ContainerApp/Engine/**'
              - 'backend/ContainerApp/EngineComponentTests/**'
              - 'backend/ContainerApp/Directory.Build.props'

      - name: Build service list
        id: set-services
        run: |
          echo "::group::Evaluating changed services"
          SERVICES=()
          if [ "${{ steps.filter.outputs.engine }}" == 'true' ]; then
            echo "Engine changed ✅"
            SERVICES+=("Engine")
          else
            echo "Engine not changed ❌"
          fi

          if [ ${#SERVICES[@]} -eq 0 ]; then
            JSON="[]"
          else
            JSON=$(printf '%s\n' "${SERVICES[@]}" | jq -R . | jq -s .)
          fi

          echo "Detected services array: ${SERVICES[@]}"
          echo "Detected services JSON: ${JSON}"

          echo "services=${JSON}" >> "$GITHUB_OUTPUT"
          echo "::endgroup::"

  call-component-tests:
    needs: changes
    if: needs.changes.outputs.services != '[]'
    uses: ./.github/workflows/component-tests.yml
    with:
      services: ${{ join(fromJson(needs.changes.outputs.services), ',') }}
      testFilter: ''
    secrets: inherit
