name: Terraform Apply (Dynamic Environment)
run-name: >
  🚀 Deploy Infrastructure to ${{
    inputs.environment_name || github.event.inputs.environment_name || 
    (inputs.environment == 'Development' && 'dev') ||
    (inputs.environment == 'Production' && 'prod') ||
    'custom'
  }} environment [${{ inputs.environment || github.event.inputs.environment }}]
   
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      environment_name:
        required: false
        type: string  
    outputs:
      static_web_app_api_token:
        description: "Azure Static Web Apps deployment token"
        value: ${{ jobs.terraform.outputs.static_web_app_api_token }}
      app_insights_connection_string:
        description: "Application Insights connection string"
        value: ${{ jobs.terraform.outputs.app_insights_connection_string }}
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (GitHub Environment)'
        required: true
        default: 'Development'
        type: choice
        options: [Development, Production]
      environment_name:
        description: 'Enter custom prefix (lowercase letters & digits only). This will be used as the Kubernetes namespace and environment identifier.'
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || github.event.inputs.environment }}
    permissions:
      id-token: write      # Required for OIDC login
      contents: read       # For actions/checkout
    
    outputs:
      static_web_app_api_token: ${{ steps.terraform_outputs.outputs.static_web_app_api_token }}
      app_insights_connection_string: ${{ steps.terraform_outputs.outputs.app_insights_connection_string }}

    env:
      ARM_USE_OIDC: "true" # tell provider to use the OIDC token
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_AZUREAD: "true" # matches `use_azuread_auth = true`

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set Terraform working directory
        run: echo "TF_DIR=./devops/terraform" >> $GITHUB_ENV

      - name: Extract and validate environment variables
        id: extract_env
        run: |
          # Determine which environment_name to use (custom or predefined)
          if [ -n "${{ inputs.environment_name }}" ]; then
            CUSTOM_ENV="${{ inputs.environment_name }}"
          elif [ -n "${{ github.event.inputs.environment_name }}" ]; then
            CUSTOM_ENV="${{ github.event.inputs.environment_name }}"
          else
            CUSTOM_ENV=""
          fi
          
          # Set environment variables based on input
          if [ -n "$CUSTOM_ENV" ]; then
            # Custom environment
            ENVIRONMENT_NAME="$CUSTOM_ENV"
            TFVARS_FILE="terraform.tfvars.template"
          else
            # Predefined environments
            case "${{ inputs.environment || github.event.inputs.environment }}" in
              "Development")
                ENVIRONMENT_NAME="dev"
                TFVARS_FILE="terraform.tfvars.dev"
                ;;
              "Production")
                ENVIRONMENT_NAME="prod"
                TFVARS_FILE="terraform.tfvars.prod"
                ;;
              *)
                echo "Unknown environment: ${{ inputs.environment || github.event.inputs.environment }}"
                exit 1
                ;;
            esac
          fi
          
          echo "environment_name=$ENVIRONMENT_NAME" >> $GITHUB_ENV
          echo "TFVARS_FILE=$TFVARS_FILE" >> $GITHUB_ENV

      - name: Generate dynamic backend key
        run: |
          BACKEND_KEY="${{ env.environment_name }}.terraform.tfstate"
          echo "backend_key=$BACKEND_KEY" >> $GITHUB_ENV

      - name: Terraform Init with dynamic backend
        run: |
          terraform init \
            -backend-config="key=${{ env.backend_key }}" \
            -reconfigure
        working-directory: ${{ env.TF_DIR }}
      
      - name: Terraform vars file
        working-directory: ${{ env.TF_DIR }}
        run: |
          if [ -f "${{ env.TFVARS_FILE }}" ] && [ "${{ env.TFVARS_FILE }}" == "terraform.tfvars.template" ]; then
            echo "" >> terraform.tfvars.template
            echo "#------------- Dynamic Environment Configuration -------------" >> terraform.tfvars.template
            echo "environment_name = \"${{ env.environment_name }}\"" >> terraform.tfvars.template
            echo "kubernetes_namespace = \"${{ env.environment_name }}\"" >> terraform.tfvars.template
          fi

          
 
      - name: Terraform Plan
        run: terraform plan -var-file=${{ env.TFVARS_FILE }}
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=${{ env.TFVARS_FILE }}
        working-directory: ${{ env.TF_DIR }}

      - name: Extract Terraform Outputs
        id: terraform_outputs
        run: |
          # Extract outputs for frontend deployment
          echo "static_web_app_api_token=$(terraform output -raw static_web_app_api_key)" >> $GITHUB_OUTPUT
          echo "app_insights_connection_string=$(terraform output -raw application_insights_connection_string)" >> $GITHUB_OUTPUT
        working-directory: ${{ env.TF_DIR }}