name: Azure Login Test

on:
  workflow_dispatch:

jobs:
  login-check:
    environment: Development
    runs-on: ubuntu-latest

    permissions:
      id-token: write      # Required for OIDC login
      contents: read       # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show current Azure account
        run: az account show