name: Deploy Azure Function App

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Development

    permissions:
      id-token: write
      contents: read

    env:
      AZURE_APP_NAME: fa-azurefunctions-dev-rg   # ⬅️ Replace this
      AZURE_RG: azurefunctions-dev-rg            # ⬅️ Your resource group

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login via OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: Publish Function App
      run: dotnet publish -c Release -o ./publish
      working-directory: devops/AzureFunctions/Solution1/TriggerCheck

    - name: Zip function app package
      run: zip -r functionapp.zip ./*
      working-directory: devops/AzureFunctions/Solution1/TriggerCheck/publish

    - name: Deploy using zip deploy (Kudu)
      run: |
        az functionapp deployment source config-zip \
          --name $AZURE_APP_NAME \
          --resource-group $AZURE_RG \
          --src functionapp.zip
      working-directory: devops/AzureFunctions/Solution1/TriggerCheck/publish

    - name: Set WEBSITE_RUN_FROM_PACKAGE setting
      run: |
        az functionapp config appsettings set \
          --name $AZURE_APP_NAME \
          --resource-group $AZURE_RG \
          --settings WEBSITE_RUN_FROM_PACKAGE=1

