name: test CICD

on:
  push:
      branches:
        - yosef/Create-a-ready-made-terraform-for-different-environments
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'Development'
        type: choice
        options:
          - Development
          - Production
      environment_type:
        description: 'Select environment type'
        required: true
        default: 'Shared'
        type: choice
        options:
          - Shared
          - Dedicated
          - Ephemeral

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment details
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Environment Type: ${{ github.event.inputs.environment_type }}"

      - name: Run a demo command
        run: echo "This is a demo job for the CICD workflow."
      
      - name: Final step
        run: echo "CICD workflow completed successfully."