name: test CICD ddddddd

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enter environment name'
        required: true
        default: 'Development'
        type: string

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment details
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"

      - name: Run a demo command
        run: echo "This is a demo job for the CICD workflow."
      
      - name: Final step
        run: echo "CICD workflow completed successfully."