name: AKS - Deploy Current Backend Images (and refresh pods)
# Builds and pushs current backend images (from current main) into acr
# and refreshes the pods with the new images.
on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'  # Only trigger for Azure backend changes
      # - '.github/workflows/build-and-push-images.yaml'  # Trigger on workflow changes
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'Development'
        type: choice
        options:
          - Development
          - Production
      environment_name:
        description: 'Enter custom prefix (used for Kubernetes namespace, etc.)'
        required: true
        type: string
      list_services_names:
        description: 'Optional comma-separated list of services to build (e.g., accessor,manager). Leave empty for all.'
        required: false
        type: string
        default: ''
        
jobs:
  set-defaults:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.defaults.outputs.environment }}
      environment_name: ${{ steps.defaults.outputs.environment_name }}
      list_services_names: ${{ steps.defaults.outputs.list_services_names }}
    steps:
      - name: Set default values
        id: defaults
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "environment=Development" >> $GITHUB_OUTPUT
            echo "environment_name=dev" >> $GITHUB_OUTPUT
            echo "list_services_names=" >> $GITHUB_OUTPUT
          else
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
            echo "environment_name=${{ github.event.inputs.environment_name }}" >> $GITHUB_OUTPUT
            echo "list_services_names=${{ github.event.inputs.list_services_names }}" >> $GITHUB_OUTPUT
          fi

  build-and-push-images:
    needs: [set-defaults]
    uses: ./.github/workflows/build-and-push-images.yaml
    permissions:
      id-token: write
      contents: read
    with:
      environment: ${{ needs.set-defaults.outputs.environment }}
      environment_name: ${{ needs.set-defaults.outputs.environment_name }}
      list_services_names: ${{ needs.set-defaults.outputs.list_services_names }}
    secrets: inherit

  helm-deploy:
    needs: [set-defaults, build-and-push-images]
    uses: ./.github/workflows/aks-app-helm-deploy.yaml
    permissions:
      id-token: write
      contents: read
    with:
      environment: ${{ needs.set-defaults.outputs.environment }}
      environment_name: ${{ needs.set-defaults.outputs.environment_name }}
      image_tag: ${{ needs.build-and-push-images.outputs.image_tag }}
    secrets: inherit
